### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by larsonthekidrs** [PixelExperience-Devices/device_oneplus_oneplus3#2]
I have been using this rom for about 2 months now. The Battery Drain is really bad. When using Bluetooth it will drain really bad. The phone will also overheat really bad. Another issue is when slightly using the device the phone will continually crash apps therefore it not being 100 percent stable. I am here to help as much as I can.

**Comment by markakash** [comment]
How can u use the rom for 2 months cause i released a new update 3 weeks ago with thermal and other fixes? I am not facing any such issue which you are saying. Try a clean flash with the latest version and see
