### ISSUE TITLE
VoLTE does not work even though the network supports it

### ISSUE THREAD

**Issue by rdx124** [PixelExperience-Devices/device_oneplus_oneplus3#4]
I was on pixel experience 9 when I ported my number to Airtel India. The device didn't show me volte option in settings. I thought it could be the issue with Airtel, but that sim was working fine on my iPhone with volte calls.
I upgraded pixel experience to 10, now I could see the menu to enable / disable volte but the calls are not being placed over VoLTE be whatever the settings of enable volte in settings. 

![Screenshot_20200816-123738435](https://user-images.githubusercontent.com/13104014/90547690-8aa4cc00-e1a9-11ea-803f-235ee37e1f57.jpg)
![Screenshot_20200816-125255419](https://user-images.githubusercontent.com/13104014/90547703-8ed0e980-e1a9-11ea-86f7-66bfe00fd6a8.jpg)

I had three days working sessions with Airtel and they said it's all fine on their end, which really is, because iPhone was placing volte calls on the same sim.

Let me know what and how can I provide more data for your rectification. 

Thanks. This is a great rom I don't want to switch out of ever.

**Comment by rdx124** [comment]
Not just Airtel but any network, VOLTE is not working at all.

**Comment by Gaurav241** [comment]
volte works in jio

**Comment by rdx124** [comment]
Closing without resolution, great!
That's pixel experience for you...

I so much miss Exodus ROM and team.

**Comment by Gaurav241** [comment]
> Closing without resolution, great!
> That's pixel experience for you...
> 
> I so much miss Exodus ROM and team.

what are you? dont you even know how to report bugs? 
and please if you don't like ROM please get rid off. no one forcing you to flash this ROM. 
And for your kind info join telegram support group (https://t.me/pixelexperienceop3). all resolution and replies are given there. this isn't how bugs are reported
